"""
haptic_system.py

Controls the vibration feedback presented to the Sense360 wearer.

The HapticSystem reads environmental information from the WorldModel and
converts that information into PWM commands for the vibration motors.

Current responsibilities:
    - Communicate with the PCA9685 PWM controller.
    - Keep track of all installed vibration motors.
    - Determine which WorldModel direction corresponds to each motor.
    - Convert obstacle distance into vibration intensity.
    - Send PWM duty-cycle commands to each motor's PCA9685 channel.
    - Turn motors off when no valid obstacle information exists.
    - Safely disable all motors during shutdown.

The HapticSystem does NOT:
    - Read ultrasonic sensors.
    - Read the BNO085 directly.
    - Modify the WorldModel.
    - Decide whether sensor measurements should be accepted or rejected.

Coordinate behavior
-------------------
Motor mounting angles are relative to the wearer:

    0 degrees   = front
    90 degrees  = right
    180 degrees = rear
    270 degrees = left

The WorldModel stores information in world-fixed directions.

Therefore, the direction represented by a motor is:

    world_angle = wearer_heading + motor_relative_angle

This allows the vibration motors to continue representing directions
relative to the wearer even while the wearer rotates.

Current Sense360 prototype:
    PCA9685:
        I2C bus 1
        Address 0x40

    Motor 1:
        PCA9685 Channel 0
        Relative angle 0 degrees
"""

from adafruit_extended_bus import ExtendedI2C as I2C
from adafruit_pca9685 import PCA9685


class HapticSystem:
    """
    Manages all Sense360 vibration motors and converts WorldModel
    distances into haptic feedback.
    """

    def __init__(
        self,
        i2c_bus: int,
        i2c_address: int,
        motors: list,
        pwm_frequency_hz: int = 200,
        feedback_min_distance_m: float = 0.20,
        feedback_max_distance_m: float = 2.00,
        min_active_intensity: float = 0.25,
        max_intensity: float = 1.00,
        intensity_curve_power: float = 1.0,
    ):
        """
        Create the HapticSystem.

        Parameters
        ----------
        i2c_bus : int
            Linux I2C bus number used by the PCA9685.

            Current Sense360 hardware:
                1 -> /dev/i2c-1

        i2c_address : int
            PCA9685 I2C address.

            Current Sense360 hardware:
                0x40

        motors : list
            Hardware configuration dictionaries describing each motor.

            Example:

                [
                    {
                        "motor_id": "motor_1",
                        "pwm_channel": 0,
                        "relative_angle_deg": 0.0,
                    }
                ]

        pwm_frequency_hz : int
            PWM frequency generated by the PCA9685.

        feedback_min_distance_m : float
            Distance at which maximum vibration intensity is reached.

            Obstacles closer than this distance also use maximum
            intensity.

        feedback_max_distance_m : float
            Maximum obstacle distance that produces vibration.

            Obstacles farther away produce no vibration.

        min_active_intensity : float
            Lowest non-zero motor intensity.

            Small vibration motors may not reliably start at extremely
            low PWM duty cycles, so active feedback can begin at some
            minimum value.

        max_intensity : float
            Maximum allowed vibration intensity.

            1.0 represents 100 percent PWM duty cycle.

        intensity_curve_power : float
            Controls the shape of the distance-to-intensity response.

            1.0:
                Linear response.

            Greater than 1.0:
                Keeps vibration weaker at longer distances and makes
                intensity increase more sharply as the obstacle gets
                close.

            Less than 1.0:
                Produces stronger vibration earlier.
        """

        if feedback_min_distance_m < 0:
            raise ValueError(
                "feedback_min_distance_m cannot be negative."
            )

        if feedback_max_distance_m <= feedback_min_distance_m:
            raise ValueError(
                "feedback_max_distance_m must be greater than "
                "feedback_min_distance_m."
            )

        if not 0.0 <= min_active_intensity <= 1.0:
            raise ValueError(
                "min_active_intensity must be between 0 and 1."
            )

        if not 0.0 <= max_intensity <= 1.0:
            raise ValueError(
                "max_intensity must be between 0 and 1."
            )

        if max_intensity < min_active_intensity:
            raise ValueError(
                "max_intensity must be greater than or equal to "
                "min_active_intensity."
            )

        if intensity_curve_power <= 0:
            raise ValueError(
                "intensity_curve_power must be greater than 0."
            )

        self.i2c_bus = i2c_bus
        self.i2c_address = i2c_address

        self.motors = motors

        self.pwm_frequency_hz = pwm_frequency_hz

        self.feedback_min_distance_m = (
            feedback_min_distance_m
        )

        self.feedback_max_distance_m = (
            feedback_max_distance_m
        )

        self.min_active_intensity = (
            min_active_intensity
        )

        self.max_intensity = max_intensity

        self.intensity_curve_power = (
            intensity_curve_power
        )

        self._closed = False

        # ---------------------------------------------------------
        # Create a lookup table for motors by ID.
        # ---------------------------------------------------------

        self.motor_lookup = {}

        for motor in self.motors:

            motor_id = motor["motor_id"]
            channel = motor["pwm_channel"]

            if motor_id in self.motor_lookup:
                raise ValueError(
                    f"Duplicate motor ID: {motor_id}"
                )

            if not 0 <= channel <= 15:
                raise ValueError(
                    f"PCA9685 channel for {motor_id} "
                    "must be between 0 and 15."
                )

            self.motor_lookup[motor_id] = motor

        # ---------------------------------------------------------
        # Store current commanded intensity for debugging/testing.
        # ---------------------------------------------------------

        self.current_intensities = {
            motor["motor_id"]: 0.0
            for motor in self.motors
        }

        # ---------------------------------------------------------
        # Open PCA9685 I2C connection.
        # ---------------------------------------------------------

        self.i2c = I2C(
            self.i2c_bus
        )

        self.pca = PCA9685(
            self.i2c,
            address=self.i2c_address,
        )

        # All PCA9685 channels share the same PWM frequency.
        self.pca.frequency = (
            self.pwm_frequency_hz
        )

        # Make sure no motor unexpectedly starts when Sense360 boots.
        self.all_off()

    def _clamp_intensity(self, intensity):
        """
        Limit an intensity value to the range 0.0 through 1.0.
        """

        return max(
            0.0,
            min(
                1.0,
                intensity,
            ),
        )

    def _intensity_to_duty_cycle(
        self,
        intensity,
        invert=False,
    ):
        """
        Convert a normalized motor intensity into PCA9685 duty cycle.

        Parameters
        ----------
        intensity : float
            Normalized motor intensity:

                0.0 = off
                1.0 = maximum output

        invert : bool
            Reverse PWM polarity if required by the motor-driver
            hardware.

        Returns
        -------
        int
            16-bit PCA9685 duty-cycle command.
        """

        intensity = self._clamp_intensity(
            intensity
        )

        if invert:
            intensity = 1.0 - intensity

        return int(
            intensity * 0xFFFF
        )

    def _distance_to_intensity(
        self,
        distance_m,
    ):
        """
        Convert obstacle distance into vibration intensity.

        Behavior:
            distance <= minimum:
                Maximum vibration.

            distance >= maximum:
                Motor off.

            distance between minimum and maximum:
                Vibration increases as distance decreases.

        Returns
        -------
        float
            Normalized intensity from 0.0 through 1.0.
        """

        if distance_m is None:
            return 0.0

        # Obstacle is outside the feedback range.
        if distance_m >= self.feedback_max_distance_m:
            return 0.0

        # Obstacle is extremely close.
        if distance_m <= self.feedback_min_distance_m:
            return self.max_intensity

        # ---------------------------------------------------------
        # Convert distance into a normalized closeness value.
        #
        # At maximum feedback distance:
        #     closeness = 0
        #
        # At minimum feedback distance:
        #     closeness = 1
        # ---------------------------------------------------------

        distance_range = (
            self.feedback_max_distance_m
            - self.feedback_min_distance_m
        )

        closeness = (
            self.feedback_max_distance_m
            - distance_m
        ) / distance_range

        # Shape the response curve.
        closeness = (
            closeness
            ** self.intensity_curve_power
        )

        # ---------------------------------------------------------
        # Scale active vibration between the minimum useful motor
        # strength and maximum motor strength.
        # ---------------------------------------------------------

        intensity = (
            self.min_active_intensity
            + closeness
            * (
                self.max_intensity
                - self.min_active_intensity
            )
        )

        return self._clamp_intensity(
            intensity
        )

    def set_motor(
        self,
        motor_id,
        intensity,
    ):
        """
        Directly command one vibration motor.

        Parameters
        ----------
        motor_id : str
            ID defined in hardware.py.

        intensity : float
            Requested vibration strength:

                0.0 = off
                1.0 = maximum

        This method is also useful for hardware testing because a motor
        can be activated without needing sensor or WorldModel data.
        """

        if self._closed:
            raise RuntimeError(
                "HapticSystem cannot be used after cleanup()."
            )

        if motor_id not in self.motor_lookup:
            raise ValueError(
                f"Unknown motor ID: {motor_id}"
            )

        motor = self.motor_lookup[
            motor_id
        ]

        channel = motor[
            "pwm_channel"
        ]

        # Allows future driver circuits to reverse PWM polarity without
        # changing HapticSystem code.
        invert_pwm = motor.get(
            "invert_pwm",
            False,
        )

        intensity = self._clamp_intensity(
            intensity
        )

        duty_cycle = (
            self._intensity_to_duty_cycle(
                intensity,
                invert=invert_pwm,
            )
        )

        self.pca.channels[
            channel
        ].duty_cycle = duty_cycle

        self.current_intensities[
            motor_id
        ] = intensity

    def get_motor_intensity(
        self,
        motor_id,
    ):
        """
        Return the most recently commanded intensity for one motor.
        """

        if motor_id not in self.current_intensities:
            raise ValueError(
                f"Unknown motor ID: {motor_id}"
            )

        return self.current_intensities[
            motor_id
        ]

    def update(
        self,
        world_model,
        heading_deg,
    ):
        """
        Update all vibration motors using the current WorldModel.

        Parameters
        ----------
        world_model : WorldModel
            Sense360's current stored environmental information.

        heading_deg : float
            Current wearer heading from MotionTracker.

        For every motor:
            1. Determine the world direction represented by that motor.
            2. Find the corresponding WorldModel cell.
            3. Read the obstacle distance stored in that direction.
            4. Convert distance into vibration intensity.
            5. Apply that intensity to the motor.
        """

        if self._closed:
            raise RuntimeError(
                "HapticSystem cannot be updated after cleanup()."
            )

        # Ensure old environmental data does not produce haptic feedback.
        world_model.clear_stale_cells()

        for motor in self.motors:

            motor_id = motor[
                "motor_id"
            ]

            relative_angle_deg = motor[
                "relative_angle_deg"
            ]

            # -----------------------------------------------------
            # Convert the motor's wearer-relative direction into
            # the corresponding world direction.
            # -----------------------------------------------------

            world_angle_deg = (
                heading_deg
                + relative_angle_deg
            ) % 360.0

            # Find environmental information in that direction.
            cell = world_model.get_cell_for_angle(
                world_angle_deg
            )

            distance_m = cell.distance_m

            # Convert the stored obstacle distance into motor strength.
            intensity = self._distance_to_intensity(
                distance_m
            )

            self.set_motor(
                motor_id,
                intensity,
            )

    def all_off(self):
        """
        Turn every vibration motor off.
        """

        if self._closed:
            return

        for motor in self.motors:

            motor_id = motor[
                "motor_id"
            ]

            self.set_motor(
                motor_id,
                0.0,
            )

    def cleanup(self):
        """
        Safely shut down the haptic hardware.

        All motors are turned off before the PCA9685 and I2C resources
        are released.
        """

        if self._closed:
            return

        # Always stop motors first.
        self.all_off()

        try:
            self.pca.deinit()
        except Exception:
            pass

        try:
            self.i2c.deinit()
        except Exception:
            pass

        self._closed = True